version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      all-go:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /build/measurement-agent
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /build/aggregation-service
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: ["*"]
