// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: measurement/v1/measurement.proto

package measurementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WindowReport is sent by a measurement agent at the end of each measurement
// window. It carries energy, token counts, and stability metadata.
type WindowReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque ID generated by the agent; used for deduplication.
	WindowId string `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	// Kubernetes node name the agent is running on.
	Node string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Name of the model being served (from inference provider label).
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// GPU energy consumed during this window in joules.
	EnergyJoules float64 `protobuf:"fixed64,4,opt,name=energy_joules,json=energyJoules,proto3" json:"energy_joules,omitempty"`
	// Cumulative output tokens at window end (aggregation service deltas these).
	OutputTokens uint64 `protobuf:"varint,5,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// GPU power draw snapshot taken at window end, in watts.
	PowerWatts float64 `protobuf:"fixed64,6,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	// Whether the CV gate passed (CV < 3%) for this window.
	Stable bool `protobuf:"varint,7,opt,name=stable,proto3" json:"stable,omitempty"`
	// Coefficient of variation for this window.
	Cv float64 `protobuf:"fixed64,8,opt,name=cv,proto3" json:"cv,omitempty"`
	// Energy provider identifier (e.g. "zeus", "nvml").
	EnergyProvider string `protobuf:"bytes,9,opt,name=energy_provider,json=energyProvider,proto3" json:"energy_provider,omitempty"`
	// Inference provider identifier (e.g. "vllm", "generic-prometheus").
	InferenceProvider string `protobuf:"bytes,10,opt,name=inference_provider,json=inferenceProvider,proto3" json:"inference_provider,omitempty"`
	// Unix timestamp in milliseconds at the end of the window.
	TimestampUnixMs int64 `protobuf:"varint,11,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WindowReport) Reset() {
	*x = WindowReport{}
	mi := &file_measurement_v1_measurement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowReport) ProtoMessage() {}

func (x *WindowReport) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_v1_measurement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowReport.ProtoReflect.Descriptor instead.
func (*WindowReport) Descriptor() ([]byte, []int) {
	return file_measurement_v1_measurement_proto_rawDescGZIP(), []int{0}
}

func (x *WindowReport) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *WindowReport) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WindowReport) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *WindowReport) GetEnergyJoules() float64 {
	if x != nil {
		return x.EnergyJoules
	}
	return 0
}

func (x *WindowReport) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *WindowReport) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *WindowReport) GetStable() bool {
	if x != nil {
		return x.Stable
	}
	return false
}

func (x *WindowReport) GetCv() float64 {
	if x != nil {
		return x.Cv
	}
	return 0
}

func (x *WindowReport) GetEnergyProvider() string {
	if x != nil {
		return x.EnergyProvider
	}
	return ""
}

func (x *WindowReport) GetInferenceProvider() string {
	if x != nil {
		return x.InferenceProvider
	}
	return ""
}

func (x *WindowReport) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// WindowAck is returned by the aggregation service after processing a report.
type WindowAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the report was accepted for aggregation.
	// False means the window was rejected (e.g. unstable, duplicate window_id).
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowAck) Reset() {
	*x = WindowAck{}
	mi := &file_measurement_v1_measurement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowAck) ProtoMessage() {}

func (x *WindowAck) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_v1_measurement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowAck.ProtoReflect.Descriptor instead.
func (*WindowAck) Descriptor() ([]byte, []int) {
	return file_measurement_v1_measurement_proto_rawDescGZIP(), []int{1}
}

func (x *WindowAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_measurement_v1_measurement_proto protoreflect.FileDescriptor

const file_measurement_v1_measurement_proto_rawDesc = "" +
	"\n" +
	" measurement/v1/measurement.proto\x12\x0emeasurement.v1\"\xf5\x02\n" +
	"\fWindowReport\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12#\n" +
	"\renergy_joules\x18\x04 \x01(\x01R\fenergyJoules\x12#\n" +
	"\routput_tokens\x18\x05 \x01(\x04R\foutputTokens\x12\x1f\n" +
	"\vpower_watts\x18\x06 \x01(\x01R\n" +
	"powerWatts\x12\x16\n" +
	"\x06stable\x18\a \x01(\bR\x06stable\x12\x0e\n" +
	"\x02cv\x18\b \x01(\x01R\x02cv\x12'\n" +
	"\x0fenergy_provider\x18\t \x01(\tR\x0eenergyProvider\x12-\n" +
	"\x12inference_provider\x18\n" +
	" \x01(\tR\x11inferenceProvider\x12*\n" +
	"\x11timestamp_unix_ms\x18\v \x01(\x03R\x0ftimestampUnixMs\"'\n" +
	"\tWindowAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2]\n" +
	"\x12MeasurementService\x12G\n" +
	"\fReportWindow\x12\x1c.measurement.v1.WindowReport\x1a\x19.measurement.v1.WindowAckBHZFgithub.com/aitra-ai/aitra-meter/api/proto/measurement/v1;measurementv1b\x06proto3"

var (
	file_measurement_v1_measurement_proto_rawDescOnce sync.Once
	file_measurement_v1_measurement_proto_rawDescData []byte
)

func file_measurement_v1_measurement_proto_rawDescGZIP() []byte {
	file_measurement_v1_measurement_proto_rawDescOnce.Do(func() {
		file_measurement_v1_measurement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_measurement_v1_measurement_proto_rawDesc), len(file_measurement_v1_measurement_proto_rawDesc)))
	})
	return file_measurement_v1_measurement_proto_rawDescData
}

var file_measurement_v1_measurement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_measurement_v1_measurement_proto_goTypes = []any{
	(*WindowReport)(nil), // 0: measurement.v1.WindowReport
	(*WindowAck)(nil),    // 1: measurement.v1.WindowAck
}
var file_measurement_v1_measurement_proto_depIdxs = []int32{
	0, // 0: measurement.v1.MeasurementService.ReportWindow:input_type -> measurement.v1.WindowReport
	1, // 1: measurement.v1.MeasurementService.ReportWindow:output_type -> measurement.v1.WindowAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_measurement_v1_measurement_proto_init() }
func file_measurement_v1_measurement_proto_init() {
	if File_measurement_v1_measurement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_measurement_v1_measurement_proto_rawDesc), len(file_measurement_v1_measurement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_measurement_v1_measurement_proto_goTypes,
		DependencyIndexes: file_measurement_v1_measurement_proto_depIdxs,
		MessageInfos:      file_measurement_v1_measurement_proto_msgTypes,
	}.Build()
	File_measurement_v1_measurement_proto = out.File
	file_measurement_v1_measurement_proto_goTypes = nil
	file_measurement_v1_measurement_proto_depIdxs = nil
}
